server {
    listen 80;
    server_name _; # 监听所有外部访问的 IP 或域名

    # 把所有的请求，转发给背后的 Flask 兄弟
    location / {
        proxy_pass http://app:5000; # 这里的 "app" 是咱们接下来在 compose 里定义的名字
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
} 